[package]
name = "smolnet"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["net_header", "net_header/meta", "."]

[features]
axum = ["dep:axum"]

[dependencies]
axum = { version = "0.8", optional = true }
net_header = { path = "./net_header" }
nix = { version = "0.31.3", features = ["ioctl", "poll", "fs"] }
rand = "0.10.2"
thiserror = "2.0.20"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "time", "sync", "io-util", "macros", "net"] }
tracing = "0.1.44"

[dev-dependencies]
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[[example]]
name = "axum_hello"
required-features = ["axum"]
