[workspace]
resolver = "3"
members = [
    "net_header",
    "net_header/meta",
    "smol",
    "smolctl",
    "smolmesh",
    "smolnet",
    "smolnode",
    "smolrun",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
net_header = { path = "net_header" }
smolctl = { path = "smolctl" }
smolmesh = { path = "smolmesh" }
smolnet = { path = "smolnet" }
smolnode = { path = "smolnode" }
smolrun = { path = "smolrun" }

clap = { version = "4", features = ["derive", "env"] }
libc = "0.2"
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "sync", "time", "io-util", "signal"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
