[package]
name = "smolmesh"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2"
rand = "0.10.2"
snow = "0.10"
x25519-dalek = { version = "2", features = ["static_secrets"] }
smolnet = { path = "../smolnet" }
thiserror = "2.0.20"
tokio = { version = "1", features = ["net", "rt", "sync", "time", "macros"] }
tracing = "0.1.44"
hickory-server = "0.26"
hickory-resolver = "0.26"
hickory-proto = "0.26"
async-trait = "0.1.92"

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "io-util"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
